### ISSUE TITLE
Doesn't work on 2.7

### ISSUE THREAD

**Issue by zoomorph** [shlomif/python-vnu_validator#2]
url.parse import

**Comment by shlomif** [comment]
Should be fixed in v0.4.3. But please do not use python 2.x - see https://legacy.python.org/dev/peps/pep-0373/ . There were also other incompats.

**Comment by sergiomb2** [comment]
I just find a another pyvnu https://github.com/rsommer/pyvnu, is so difficult give a palin and simple example ? test unit is not simple
