### ISSUE TITLE
please provide an example 

### ISSUE THREAD

**Issue by sergiomb2** [shlomif/python-vnu_validator#5]
Hi,
This can be very useful but I can't start it 

usage says `import vnu_validator` and then what ?

**Comment by shlomif** [comment]
On Thu, 17 Dec 2020 03:53:34 -0800
Sérgio Basto <notifications@github.com> wrote:

> Hi,
> This can be very useful but I can't start it 
> 
> usage says `import vnu_validator` than what ? 
> 

Sounds like a useful suggestion. see:

https://github.com/shlomif/perl-begin/blob/master/Tests/validate-html-using-vnu.py

for an example. Please file a pull-req if you know offhand how to fix it.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/Can-I-SCO-Now/ - “Can I SCO Now?”

That’s why I feed my leprechaun every day — because there are not enough
phonemes in Navajo to tell him to get his act together and find a job.
    — My comment on https://www.youtube.com/watch?v=izne8XcaBBg .

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by sergiomb2** [comment]
I just find a another pyvnu https://github.com/rsommer/pyvnu, is so difficult give a plain and simple example ? test unit is not simple

I also like the expression "basic use"

**Comment by sergiomb2** [comment]
I tried 

```
unzip vnu.jar_20.6.30.zip 
j = vnu_validator.VnuSingleFileValidate("/home/sergio/index.html", "/home/sergio/dist/vnu.jar" , True)
j.run()
```

but 


```
--------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
<ipython-input-27-31d72505e0c8> in <module>()
----> 1 j.run()

/home/genuser/.local/lib/python3.6/site-packages/vnu_validator/__init__.py in run(self)
    161         tname = tempfile.mkdtemp()
    162         open(join(tname, "foo.html"), 'wb').write(open(self.path, 'rb').read())
--> 163         verdict = VnuValidate(tname, self.jar, self.non_xhtml_cb, lambda p: False).run()
    164         _temp_rmtree(tname)
    165         return verdict

/home/genuser/.local/lib/python3.6/site-packages/vnu_validator/__init__.py in run(self)
     85         for dirpath, _, fns in os.walk(self.path):
     86             dn = _mytrim(join(tname, _mytrim(dirpath)))
---> 87             os.makedirs(dn)
     88             for fn in fns:
     89                 path = _mytrim(join(dirpath, fn))

/usr/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    218             return
    219     try:
--> 220         mkdir(name, mode)
    221     except OSError:
    222         # Cannot rely on checking for EEXIST, since the operating system

FileExistsError: [Errno 17] File exists: '/tmp/tmpf3dt48ai'

```

**Comment by shlomif** [comment]
@sergiomb2 : hi! this should hopefully be fixed in the 0.8.3. It uncovered some tangential bugs, so - thanks:

```
shlomif[homepage]:$trunk$ python3 ~/progs/python/vnu/python-vnu_validator/examples/single_file_check.py --filename dest/post-incs/t2/open-source/resources/databases-list/index.xhtml
fn = dest/post-incs/t2/open-source/resources/databases-list/index.xhtml
java -jar /home/shlomif/Download/unpack/net/www/validator/build/dist/vnu.jar --format json --Werror --skip-non-html /tmp/tmpn58ku7m9
shlomif[homepage]:$trunk$ 
```

Do note that the intention of this python module is to be a framework for writing tests rather than a simple-minded wrapper.

**Comment by sergiomb2** [comment]
Hi, first many thanks
yes the example is working , but only with files. I goal is test all pages of my sites in development i.e.  in localhost , but now is easy to fix ... 
I'm afraid that I don't know how to work with "framework for writing tests rather than a simple-minded wrapper" but I'd love to learn how 

```
import vnu_validator 
j = vnu_validator.VnuSingleFileValidate("http://localhost:8001/", "/home/sergio/dist/vnu.jar" , True)
j.run()
```

FileNotFoundError: [Errno 2] No such file or directory: 'http://localhost:8001/'

**Comment by shlomif** [comment]
Hi @sergiomb2 !

> Hi, first many thanks
> yes the example is working , but only with files. I goal is test all pages of my sites in development i.e. in localhost , but now is easy to fix ...
> I'm afraid that I don't know how to work with "framework for writing tests rather than a simple-minded wrapper" but I'd love to learn how
> 
> ```
> import vnu_validator 
> j = vnu_validator.VnuSingleFileValidate("http://localhost:8001/", "/home/sergio/dist/vnu.jar" , True)
> j.run()
> ```
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'http://localhost:8001/'

Neither the unix file system system calls nor python's [open() builtin](https://docs.python.org/3/library/functions.html#open) can open URLs. PHP's [fopen()](https://www.php.net/manual/en/function.fopen.php) conflates both uses, and it is often a security issue.

You can try mirroring the pages of the localhost site into the filesystem using a web crawler, or perhaps use a python equivalent to [Inline-Java](https://metacpan.org/pod/distribution/Inline-Java/lib/Inline/Java.pod) .

**Comment by shlomif** [comment]
@sergiomb2 : ping! It has been 4 months.

**Comment by sergiomb2** [comment]
> Neither the unix file system system calls nor python's open() builtin can open URLs. PHP's fopen() conflates both uses, and it is often a security issue.

yes it can with urllib3 or something like it , I will try review this on weekend ... or we do wget "http://localhost:8001/" before

**Comment by shlomif** [comment]
> > Neither the unix file system system calls nor python's open() builtin can open URLs. PHP's fopen() conflates both uses, and it is often a security issue.
> 
> yes it can with urllib3 or something like it , I will try review this on weekend ... or we do wget "http://localhost:8001/" before

Hi @sergiomb2 ! Any update? You're stressing my patience. "wget"/etc. should be an adequate solution.

**Comment by sergiomb2** [comment]
Sorry , I know , I have a lot of excuses  , I'd like use this in my $dayjob , turn out is was an priority .... 

[downloadfile.py.txt](https://github.com/shlomif/python-vnu_validator/files/7387876/downloadfile.py.txt)

unfortunately my code just works on python 2 , but here is the code that I like to adapt.

**Comment by sergiomb2** [comment]
sorry this downloadfile.py , is part of a project on in previous $dayjob , it needs config files , so doesn't work even with python 2.  I will try it today !

**Comment by shlomif** [comment]
@sergiomb2 : I see. thanks for the headsup.

**Comment by sergiomb2** [comment]
ok, sorry for the delay, my PR worked in my basic test.

downloadcontent.py is prepared to deal with complicated server responses and we can set headers, we can set cookies,  referer etc but I don't know if is useful in this project

**Comment by shlomif** [comment]
Rejecting for now, to avoid clutter.
